# This file was generated by GoReleaser. DO NOT EDIT.
cask "hiive" do
  name "hiive"
  desc "A command line interface for everything Hiive related."
  homepage ""
  version "1.12.1"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "hiive"
  manpage "man/hiive.1"
  bash_completion "completions/hiive.bash"
  zsh_completion "completions/_hiive"
  fish_completion "completions/hiive.fish"

  on_macos do
    on_intel do
      url "https://homebrew.hiive.network/cli/v#{version}/hiive_#{version}_darwin_amd64.tar.gz"
      sha256 "83a354777932c5c87ab323f72f5ef377cebcc1f98544574488cd97719980d02f"
    end
    on_arm do
      url "https://homebrew.hiive.network/cli/v#{version}/hiive_#{version}_darwin_arm64.tar.gz"
      sha256 "98e9133933c60a98cc18d292e7f077c6ea47bb5171b5eabb541bcb30c6129821"
    end
  end

  on_linux do
    on_intel do
      url "https://homebrew.hiive.network/cli/v#{version}/hiive_#{version}_linux_amd64.tar.gz"
      sha256 "58e4d0df2854b9cb30ca74d3f4b4066d58ef824c8d7fd631d5aa08e6212793e8"
    end
    on_arm do
      url "https://homebrew.hiive.network/cli/v#{version}/hiive_#{version}_linux_arm64.tar.gz"
      sha256 "24b4955f638c96f83751253575f706b15bdcc45e9e20b89e982af6dc681d353d"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/hiive"]
    end
  end

  # No zap stanza required
end
